{
 "title": "Monitoring App - Performance",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": {
     "query": "label_values(hikaricp_connections{job=\"app-spring\"}, pool)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Physical CPU load",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"app-host\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',job=\"app-host\"}[1m])))) * 100) / count(count(node_cpu_seconds_total{job=\"app-host\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Physical Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"app-host\"} / (node_memory_MemTotal_bytes{job=\"app-host\"})))* 100"
    }
   ]
  },
  {
   "title": "Physical CPU load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{job=\"app-host\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Disk Read/Write",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg by (device) (irate(node_disk_read_bytes_total{ job=\"app-host\"}[1m]))",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "avg by (device) (irate(node_disk_written_bytes_total{ job=\"app-host\"}[1m]))",
     "legendFormat": "{{device}} write"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{ job=\"app-host\"}[1m])",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{ job=\"app-host\"}[1m])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  },
  {
   "title": "Threads / Connections / Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Java Threads",
   "type": "graph",
   "gridPos": { "h": 16, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{job=\"app-spring\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "jvm_threads_live_threads{job=\"app-spring\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon_threads{job=\"app-spring\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{job=\"app-spring\"}",
     "legendFormat": "peak"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=\"app-host\"}",
     "legendFormat": "Established"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=\"app-host\"}",
     "legendFormat": "tw"
    },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{job=\"app-host\"}[1m])",
     "legendFormat": "ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{job=\"app-host\"}[1m])",
     "legendFormat": "PassiveOpens"
    },
    {
     "expr": "node_sockstat_TCP_alloc{job=\"app-host\"}",
     "legendFormat": "alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{job=\"app-host\"}",
     "legendFormat": "inuse"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=\"app-host\"}",
     "legendFormat": "Established"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=\"app-host\"}",
     "legendFormat": "tw"
    },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{job=\"app-host\"}[1m])",
     "legendFormat": "ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{job=\"app-host\"}[1m])",
     "legendFormat": "PassiveOpens"
    },
    {
     "expr": "node_sockstat_TCP_alloc{job=\"app-host\"}",
     "legendFormat": "alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{job=\"app-host\"}",
     "legendFormat": "inuse"
    }
   ]
  },
  {
   "title": "Tomcat Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_threads_current_threads{job=\"app-spring\"}",
     "legendFormat": "Current Thread"
    },
    {
     "expr": "tomcat_threads_config_max_threads{job=\"app-spring\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_active{job=\"app-spring\", pool=\"$hikaricp\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "hikaricp_connections_idle{job=\"app-spring\", pool=\"$hikaricp\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "hikaricp_connections_pending{job=\"app-spring\", pool=\"$hikaricp\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  { "title": "Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Http Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{job=\"app-spring\", exception=\"None\", uri!~\".*actuator.*\"}[5m]) / irate(http_server_requests_seconds_count{job=\"app-spring\", exception=\"None\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Database Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(spring_data_repository_invocations_seconds_sum{job=\"app-spring\", exception=\"None\", uri!~\".*actuator.*\"}[5m]) / irate(spring_data_repository_invocations_seconds_count{job=\"app-spring\", exception=\"None\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Network Input",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{image!=\"\", name=\"appspring\",job=\"app-cont\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Network Output",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\", name=\"appspring\",job=\"app-cont\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Tomcat Network",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(tomcat_global_received_bytes_total{job=\"app-spring\"}[1m])",
     "legendFormat": "received"
    },
    {
     "expr": "irate(tomcat_global_sent_bytes_total{job=\"app-spring\"}[1m])",
     "legendFormat": "sent"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "ERROR logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{job=\"app-spring\", level=\"error\"}[5m])",
     "legendFormat": "error",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}