{
 "title": "Monitoring Client",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Service/Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UpTime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{id=~\"/docker/.*\",job=\"cli-cont\"})"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"cli-host\",mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"cli-host\"} / (node_memory_MemTotal_bytes{job=\"cli-host\"})))* 100"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{job=\"cli-host\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{job=\"cli-host\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes {job=\"cli-host\",fstype=~\"ext4|xfs\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "System Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"cli-host\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',job=\"cli-host\"}[1m])))) * 100) / count(count(node_cpu_seconds_total{job=\"cli-host\"}) by (cpu))",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "\n(1 - (node_memory_MemAvailable_bytes{job=\"cli-host\"} / (node_memory_MemTotal_bytes{job=\"cli-host\"})))* 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "% Disk Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{job=\"cli-host\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{job=\"cli-host\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Read/Write",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg by (device) (irate(node_disk_read_bytes_total{ job=\"cli-host\"}[1m]))",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "avg by (device) (irate(node_disk_written_bytes_total{ job=\"cli-host\"}[1m]))",
     "legendFormat": "{{device}} write"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{ job=\"cli-host\"}[1m])",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{ job=\"cli-host\"}[1m])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  },
  {
   "title": "TCP Connection situation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=\"cli-host\"}",
     "legendFormat": "Established"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=\"cli-host\"}",
     "legendFormat": "tw"
    },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{job=\"cli-host\"}[1m])",
     "legendFormat": "ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{job=\"cli-host\"}[1m])",
     "legendFormat": "PassiveOpens"
    },
    {
     "expr": "node_sockstat_TCP_alloc{job=\"cli-host\"}",
     "legendFormat": "alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{job=\"cli-host\"}",
     "legendFormat": "inuse"
    }
   ]
  },
  { "title": "Container Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Container CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_user_seconds_total{image!=\"\", job=\"cli-cont\"}[1m]))*100",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{image!=\"\",job=\"cli-cont\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Memory usage per container",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 18 },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{name!=\"\",job=\"cli-cont\"}) by (name)"
    },
    {
     "expr": "max(container_memory_max_usage_bytes{name!=\"\",job=\"cli-cont\"}-container_memory_usage_bytes{name!=\"\",job=\"cli-cont\"})by (name)"
    },
    {
     "expr": "max(container_memory_max_usage_bytes{name!=\"\",job=\"cli-cont\"}) by (name)"
    }
   ]
  },
  {
   "title": "Network Input",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{image!=\"\",job=\"cli-cont\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Network Output",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\",job=\"cli-cont\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Disk - Read",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{job=\"cli-cont\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk - Write",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{job=\"cli-cont\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}