{
 "title": "JMeter",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "percentile",
    "label": "Percentile",
    "query": {
     "query": "label_values(jmeter_rt_as_summary{code=\"200\"}, quantile)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jmeter_threads{job=\"jmeter\", state=\"active\"}"
    }
   ]
  },
  {
   "title": "Response Time (Success) per Users",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(jmeter_rt_as_summary{code=\"200\", job=\"jmeter\", quantile=\"$quantile\"}[1m])",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "sum(jmeter_threads{state=\"active\"})",
     "legendFormat": "Virtual Users"
    }
   ]
  },
  {
   "title": "ThoughtPut",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(jmeter_hist_count{job=\"jmeter\"}[1m])",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "ThroughPut",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(rate(jmeter_hist_count{job=\"jmeter\"}[1m]))"
    }
   ]
  },
  {
   "title": "Latency Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "jmeter_rt_as_summary{code=\"200\", job=\"jmeter\", quantile=\"$percentile\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Response Time (Error)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(jmeter_rt_as_summary{code!=\"200\", job=\"jmeter\", quantile=\"$quantile\"}[1m])",
     "legendFormat": "{{label}} - {{code}}"
    }
   ]
  },
  {
   "title": "Http Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{job=\"app-spring\", exception=\"None\", uri!~\".*actuator.*\"}[5m]) / irate(http_server_requests_seconds_count{job=\"app-spring\", exception=\"None\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  }
 ]
}