global:
  scrape_interval: 20s
  scrape_timeout: 10s
  evaluation_interval: 20s
  external_labels:
    monitor: Alerting
rule_files:
- 'alert.rules'
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - alertmanager:9093
scrape_configs:
  - job_name: prometheus
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: '/prometheus/metrics'
    static_configs:
    - targets:
      - localhost:9090
  - job_name: 'alertmanager'
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: '/alertmanager/metrics'
    static_configs:
    - targets:
      - 'alertmanager:9093'
  - job_name: 'grafana'
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: '/grafana/metrics'
    static_configs:
    - targets:
      - 'grafana:3000'
  - job_name: 'app-host'
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: '/metrics'
    static_configs:
    - targets:
      - 'app.server.internal:9100'
  - job_name: 'app-cont'
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
    - targets:
      - 'app.server.internal:8082'
  - job_name: 'app-spring'
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets:
      - 'app.server.internal:9095'
  - job_name: 'cli-host'
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: '/metrics'
    static_configs:
    - targets:
      - 'host.docker.internal:9100'
  - job_name: 'cli-cont'
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: '/metrics'
    static_configs:
    - targets:
      - 'cadvisor:8080'
  - job_name: 'jmeter'
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: '/metrics'
    static_configs:
    - targets:
      - 'jmeterslave1:9270'