version: '3.3'

services:
  cadvisor:
    image: google/cadvisor:v0.33.0
    container_name: 'cadvisor'
    ports:
    - 8082:8082
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk:/dev/disk/:ro
    command:
    - '-port=8082'

  database:
    container_name: database
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example
      MYSQL_LOWER_CASE_TABLE_NAMES: 1
    volumes:
      - ./mysql/data:/var/lib/mysql:rw

  adminer:
    container_name: adminer
    image: adminer:4
    ports:
    - 7777:7777
    environment:
      ADMINER_DEFAULT_SERVER: database
    command:
    - 'php'
    - '-S'
    - '[::]:7777'
    - '-t'
    - '/var/www/html'
    entrypoint:
    - 'entrypoint.sh'
    - 'docker-php-entrypoint'
    links:
    - database:database