version: '3.3'

# volumes:
#     prometheus_data: {}
#     grafana_data: {}

services:
  cadvisor:
    image: google/cadvisor:v0.33.0
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk:/dev/disk/:ro
    devices:
    - /dev/kmsg:/dev/kmsg
  prometheus:
    image: prom/prometheus:v2.31.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      # - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
#      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.external-url=http://prometheus:9090/prometheus'
    links:
      - alertmanager:alertmanager
      - cadvisor:cadvisor
    extra_hosts:
      - 'host.docker.internal:10.187.1.55'
      - 'app.server.internal:10.187.1.52'
  alertmanager:
    image: prom/alertmanager:v0.23.0
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://alertmanager:9093/alertmanager'
  grafana:
    image: grafana/grafana:8.2.2
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
#      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/:ro
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    env_file:
      - ./grafana/config.monitoring
  nginx:
    image: nginx:1.21.4-perl
    container_name: nginx
    ports:
    - 80:80
    volumes:
    - ./nginx/index.html:/usr/share/nginx/html/index.html:ro
    - ./nginx/404.html:/usr/share/nginx/html/404.html:ro
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
